<?php

return [
    'us_states' => [
        'Adak',
        'Akhiok',
        'Akiachak',
        'Akiak',
        'Akutan',
        'Alakanuk',
        'Aleknagik',
        'Allakaket',
        'Ambler',
        'Anaktuvuk Pass',
        'Anchor Point',
        'Anchorage',
        'Anderson',
        'Angoon',
        'Aniak',
        'Anvik',
        'Arctic Village',
        'Atka',
        'Atmautluak',
        'Atqasuk',
        'Barrow (Utqiaġvik)',
        'Beaver',
        'Bethel',
        'Bettles',
        'Big Lake',
        'Brevig Mission',
        'Buckland',
        'Cantwell',
        'Central',
        'Chalkyitsik',
        'Chefornak',
        'Chenega',
        'Chevak',
        'Chickaloon',
        'Chignik',
        'Chignik Lagoon',
        'Chignik Lake',
        'Chitina',
        'Chuathbaluk',
        'Circle',
        'Clam Gulch',
        'Clarks Point',
        'Coffman Cove',
        'Cold Bay',
        'Cooper Landing',
        'Copper Center',
        'Cordova',
        'Craig',
        'Crooked Creek',
        'Deering',
        'Delta Junction',
        'Dillingham',
        'Diomede',
        'Dot Lake',
        'Douglas',
        'Dutch Harbor',
        'Eagle',
        'Eagle River',
        'Edna Bay',
        'Eek',
        'Egegik',
        'Eielson AFB',
        'Eklutna',
        'Elfin Cove',
        'Elim',
        'Emmonak',
        'Evansville',
        'Excursion Inlet',
        'Fairbanks',
        'False Pass',
        'Ferry',
        'Fishhook',
        'Flat',
        'Fort Greely',
        'Fort Yukon',
        'Fox',
        'Fox River',
        'Gakona',
        'Galena',
        'Gambell',
        'Game Creek',
        'Glacier View',
        'Glennallen',
        'Golovin',
        'Goodnews Bay',
        'Grayling',
        'Gulkana',
        'Gustavus',
        'Haines',
        'Halibut Cove',
        'Happy Valley',
        'Harding-Birch Lakes',
        'Healy',
        'Healy Lake',
        'Hobart Bay',
        'Hollis',
        'Holy Cross',
        'Homer',
        'Hoonah',
        'Hooper Bay',
        'Hope',
        'Houston',
        'Hughes',
        'Huslia',
        'Hydaburg',
        'Hyder',
        'Igiugig',
        'Iliamna',
        'Iron Creek',
        'Ivanof Bay',
        'Juneau',
        'Kake',
        'Kaktovik',
        'Kalskag',
        'Kaltag',
        'Karluk',
        'Kasaan',
        'Kasigluk',
        'Kasilof',
        'Kenai',
        'Kenny Lake',
        'Ketchikan',
        'Kiana',
        'King Cove',
        'King Salmon',
        'Kipnuk',
        'Kivalina',
        'Klawock',
        'Klukwan',
        'Knik',
        'Kobuk',
        'Kodiak',
        'Kodiak Station',
        'Kokhanok',
        'Koliganek',
        'Kongiganak',
        'Kotlik',
        'Kotzebue',
        'Koyuk',
        'Koyukuk',
        'Kwethluk',
        'Kwigillingok',
        'Lake Louise',
        'Larsen Bay',
        'Lazy Mountain',
        'Levelock',
        'Lime Village',
        'Livengood',
        'Lower Kalskag',
        'Lutak',
        'Manley Hot Springs',
        'Manokotak',
        'Marshall',
        'Mekoryuk',
        'McGrath',
        'McKinley Park',
        'Meadow Lakes',
        'Minto',
        'Moose Creek',
        'Moose Pass',
        'Mountain Village',
        'Naknek',
        'Nanwalek',
        'Napaimute',
        'Napakiak',
        'Napaskiak',
        'Naukati Bay',
        'Nelchina',
        'Nelson Lagoon',
        'Nenana',
        'New Allakaket',
        'New Stuyahok',
        'Newhalen',
        'Nightmute',
        'Nikiski',
        'Nikolai',
        'Nikolski',
        'Ninilchik',
        'Noatak',
        'Nome',
        'Nondalton',
        'Noorvik',
        'North Pole',
        'Nuiqsut',
        'Nulato',
        'Nunam Iqua',
        'Nunapitchuk',
        'Old Harbor',
        'Oscarville',
        'Ouzinkie',
        'Palmer',
        'Paxson',
        'Pedro Bay',
        'Pelican',
        'Perryville',
        'Petersburg',
        'Pilot Point',
        'Pilot Station',
        'Pitkas Point',
        'Platinum',
        'Point Baker',
        'Point Hope',
        'Point Lay',
        'Port Alexander',
        'Port Alsworth',
        'Port Clarence',
        'Port Graham',
        'Port Heiden',
        'Port Lions',
        'Port Protection',
        'Prudhoe Bay',
        'Quinhagak',
        'Rampart',
        'Red Devil',
        'Red Dog Mine',
        'Ruby',
        'Russian Mission',
        'St. George',
        'St. Mary\'s',
        'St. Michael',
        'St. Paul',
        'Salcha',
        'Sand Point',
        'Savoonga',
        'Saxman',
        'Scammon Bay',
        'Selawik',
        'Seldovia',
        'Seward',
        'Shageluk',
        'Shaktoolik',
        'Sheldon Point',
        'Shishmaref',
        'Shungnak',
        'Sitka',
        'Skagway',
        'Sleetmute',
        'Soldotna',
        'Solomon',
        'South Naknek',
        'Stebbins',
        'Sterling',
        'Stevens Village',
        'Stony River',
        'Sunrise',
        'Susitna',
        'Susitna North',
        'Sutton-Alpine',
        'Takotna',
        'Talkeetna',
        'Tanacross',
        'Tanaina',
        'Tanana',
        'Tatitlek',
        'Teller',
        'Tenakee Springs',
        'Tetlin',
        'Thorne Bay',
        'Togiak',
        'Tok',
        'Toksook Bay',
        'Tolsona',
        'Tonsina',
        'Trapper Creek',
        'Tuluksak',
        'Tuntutuliak',
        'Tununak',
        'Twin Hills',
        'Two Rivers',
        'Tyonek',
        'Unalakleet',
        'Unalaska',
        'Valdez',
        'Venetie',
        'Wainwright',
        'Wales',
        'Wasilla',
        'White Mountain',
        'Whittier',
        'Willow',
        'Wiseman',
        'Wrangell',
        'Yakutat',
        'Y-K Delta',
    ],

];
